### ISSUE TITLE
S4 Agregar el detalle de la vista funcional adaptados al modelo final definido con los patrones

### ISSUE THREAD

**Issue by bemejia** [alejofig/proyecto_1#29]

**Comment by sebasarangom** [comment]
Se empieza el trabajo.

**Comment by sebasarangom** [comment]
Se completan los diagramas de la vista funcional, con las tácticas, patrones y niveles. Se suben en el documento compartido.

**Comment by sebasarangom** [comment]
Se completa y se puede cerrar el ticket.
