### ISSUE TITLE
S5 Refinar vista funcional

### ISSUE THREAD

**Issue by bemejia** [alejofig/proyecto_1#35]

**Comment by sebasarangom** [comment]
Se revisan los comentarios del tutor para refinar las vistas funcionales.

**Comment by sebasarangom** [comment]
Se refina las vistas funcionales que apliquen, agregando la parte de la persistencia no relacional que está implementada en la parte de despliegue.

**Comment by sebasarangom** [comment]
Se completa el refinamiento.
