### ISSUE TITLE
S8 Refinar vista funcional: sacar el encriptador y agregar el servicio externo de KMS

### ISSUE THREAD

**Issue by bemejia** [alejofig/proyecto_1#61]

**Comment by sebasarangom** [comment]
Se modifica la vista funcional donde se tenía el API Gateway y las tácticas de encriptacion y autenticacion, cambiando el medio de encriptación de forma que sea mediante KMS como se sugiere en el desarrollo; de esta manera se actualiza el diagrama acorde a la futura implementación.
